create database ETRADE

CREATE TABLE CUSTOMER
(
CUSTOMER_NUMBER INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME NVARCHAR(100) NOT NULL,
LAST_NAME NVARCHAR(100) NOT NULL,
BIRTHDATE DATE NOT NULL ,
PROFESSION NVARCHAR(50) NOT NULL,
GENDER VARCHAR(1) NOT NULL,
ADDRESS1 NVARCHAR(250) NOT NULL,
ADDRESS2 NVARCHAR(250) ,
PHONE VARCHAR(50) NOT NULL,
EMAIL NVARCHAR(200) NOT NULL
)

CREATE TABLE BASKET
(
BASKET_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
CUSTOMER_NUMBER INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRODUCT_NAME NVARCHAR(255) NOT NULL,
AMOUNT INT NOT NULL,
PRICE  SMALLMONEY NOT NULL,
STATUS_ SMALLINT NOT NULL,
DATE_ DATE NOT NULL
CONSTRAINT  FK_CUSTOMER_BASKET FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES CUSTOMER(CUSTOMER_NUMBER)
)


CREATE TABLE ORDER_
(
ORDER_NUMBER INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
BASKET_ID INT NOT NULL,
PRODUCT NVARCHAR(200) NOT NULL,
DATE_ DATE NOT NULL,
AMOUNT INT NOT NULL, 
PRICE INT NOT NULL,
STATUS_ TINYINT NOT NULL,
CONSTRAINT  FK_BASKET_ORDER FOREIGN KEY (BASKET_ID) REFERENCES BASKET(BASKET_ID)
)

CREATE TABLE PRODUCT 
(
PRODUCT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(255) NOT NULL,
ORDER_NUMBER INT NOT NULL,
CATEGORY_ID INT NOT NULL,
PRICE  INT NOT NULL,
DISCOUNT INT,
UNITINSTOCK INT NOT NULL,
CONSTRAINT  FK_ORDER_PRODUCT FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDER_(ORDER_NUMBER)
) 

CREATE TABLE CATEGORY 
(
CATEGORY_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
CATEGORY_NAME NVARCHAR(100) NOT NULL,
CONSTRAINT  FK_PRODUCT_CATEGORY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE PAYMENT
(
PAYMENT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ORDER_NUMBER INT NOT NULL,
PAYMENT_TYPE SMALLINT NOT NULL,
PAYMENT_STATUS VARCHAR (50) NOT NULL,
PAYMENT_AMOUNT INT NOT NULL,
CONSTRAINT  FK_ORDER_PAYMENT FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDER_(ORDER_NUMBER)
)

CREATE TABLE SUPPLIER
(
SUPPLIER_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
COMPANY_NAME VARCHAR(100) NOT NULL,
STATUS_ NVARCHAR(100) NOT NULL,
ADDRESS1 NVARCHAR(200) NOT NULL,
ADDRESS2 NVARCHAR(200),
CITY NVARCHAR(100) NOT NULL,
COUNTY NVARCHAR(100) NOT NULL,
PHONE VARCHAR(50) NOT NULL,
EMAIL NVARCHAR(250) NOT NULL,
CONSTRAINT  FK_PRODUCT_SUPPLIER FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)


CREATE TABLE SHIPPER
(
SHIPPER_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
ORDER_NUMBER INT NOT NULL,
COMPANY_NAME NVARCHAR (200) NOT NULL,
PHONE VARCHAR(50) NOT NULL,
CONSTRAINT  FK_ORDER_SUPPLIER FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDER_(ORDER_NUMBER)
)
